import { ROLES } from './roles.js';

export const PERMISSIONS = {
  SHOPS_MANAGE: 'shops:manage',
  USERS_CREATE: 'users:create',
  FINANCE_MANAGE: 'finance:manage',
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE: 'inventory:manage',
  ORDERS_VIEW: 'orders:view',
  ORDERS_MANAGE: 'orders:manage',
  AUDIT_VIEW: 'audit:view',
  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',
};

/** Maximum permissions each role can be granted (ceiling set by Super Admin policy). */
export const ROLE_PERMISSION_CEILING = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.SHOPS_MANAGE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.SHOP_MANAGER]: [
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  [ROLES.SHOP_STAFF]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
  ],
  [ROLES.STUDENT]: [],
};

/** Default grants when Super Admin does not specify custom permissions. */
export const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [...ROLE_PERMISSION_CEILING[ROLES.SUPER_ADMIN]],
  [ROLES.SHOP_MANAGER]: [...ROLE_PERMISSION_CEILING[ROLES.SHOP_MANAGER]],
  [ROLES.SHOP_STAFF]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
  ],
  [ROLES.STUDENT]: [],
};
