export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SHOP_MANAGER: 'SHOP_MANAGER',
  SHOP_STAFF: 'SHOP_STAFF',
  STUDENT: 'STUDENT',
};

export const SHOP_SCOPED_ROLES = [ROLES.SHOP_MANAGER, ROLES.SHOP_STAFF];

export const FINANCE_ALLOWED_ROLES = [ROLES.SUPER_ADMIN, ROLES.SHOP_MANAGER];

export const INVENTORY_ALLOWED_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.SHOP_MANAGER,
  ROLES.SHOP_STAFF,
];
